project_id = "dzombacjycmrahnrdsnc"

[functions.create-papi-checkout]
verify_jwt = true

[functions.papi-webhook]
verify_jwt = false

[auth]
additional_redirect_urls = [
  "https://factumation.manda-ia.com/**",
  "https://factumation.manda-ia.com",
  "https://factumation.vercel.app/**",
  "https://factumation.vercel.app",
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**",
]
site_url = "https://factumation.manda-ia.com"

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.external.google]
client_id = "802854472376-5krq6khdttjo1nb6stc9ne5f45tfiaae.apps.googleusercontent.com"
enabled = true
skip_nonce_check = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true

[storage.vector]
enabled = false
